# Generated by Django 2.0.3 on 2018-03-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.SmallIntegerField(default=0, verbose_name='被禁状态')),
                ('is_deleted', models.SmallIntegerField(default=0, verbose_name='删除状态')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宠物信息',
                'db_table': 'pet_petInfo',
                'verbose_name_plural': '宠物信息',
            },
        ),
    ]
