# Generated by Django 2.0.3 on 2018-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='评论内容')),
                ('is_blocked', models.SmallIntegerField(default=0, verbose_name='被禁状态')),
                ('is_deleted', models.SmallIntegerField(default=0, verbose_name='删除状态')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'pet_comment',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'pet_favorite',
            },
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_id', models.IntegerField(default=0, verbose_name='排序id')),
                ('name', models.CharField(default='未知', max_length=32, unique=True, verbose_name='类别名')),
                ('cover', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='封面')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宠物类别',
                'verbose_name_plural': '宠物类别',
                'db_table': 'pet_category',
            },
        ),
        migrations.AlterModelTable(
            name='petinfo',
            table='pet_pet_info',
        ),
    ]
