# Generated by Django 2.0.3 on 2018-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登录'),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='signature',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='个性签名'),
        ),
    ]
